package org.artkachenko.kmp_learning_app.curriculum.learning.validation

/**
 * Why a piece of authored learning content was rejected.
 *
 * The set is intentionally fine-grained: the validator exists to tell an author what to
 * fix, and a single generic "invalid learning content" code would push that work back onto
 * whoever reads the failure.
 */
internal enum class LearningCurriculumValidationErrorCode {
    BLANK_UNIT_ID,
    DUPLICATE_UNIT_ID,
    BLANK_UNIT_TITLE,
    PLACEHOLDER_UNIT_TITLE,
    BLANK_UNIT_SUMMARY,
    PLACEHOLDER_UNIT_SUMMARY,
    BLANK_HOME_TOPIC_ID,
    UNKNOWN_HOME_TOPIC,
    NO_LESSONS,

    BLANK_LESSON_ID,
    DUPLICATE_LESSON_ID,
    BLANK_LESSON_TITLE,
    PLACEHOLDER_LESSON_TITLE,
    BLANK_LESSON_SUMMARY,
    PLACEHOLDER_LESSON_SUMMARY,

    NO_PRIMARY_SUBTOPICS,
    BLANK_PRIMARY_SUBTOPIC_ID,
    UNKNOWN_PRIMARY_SUBTOPIC,
    DUPLICATE_PRIMARY_SUBTOPIC_ID,
    BLANK_SUPPORTING_SUBTOPIC_ID,
    UNKNOWN_SUPPORTING_SUBTOPIC,
    DUPLICATE_SUPPORTING_SUBTOPIC_ID,
    PRIMARY_SUPPORTING_SUBTOPIC_OVERLAP,

    BLANK_RELATED_LESSON_ID,
    DUPLICATE_RELATED_LESSON_ID,
    UNKNOWN_RELATED_LESSON,
    SELF_RELATED_LESSON,

    NO_SECTIONS,
    EMPTY_SECTION_BLOCKS,
    BLANK_SECTION_TITLE,
    PLACEHOLDER_SECTION_TITLE,

    BLANK_PARAGRAPH_TEXT,
    PLACEHOLDER_PARAGRAPH_TEXT,
    EMPTY_BULLET_LIST,
    BLANK_BULLET_ITEM,
    PLACEHOLDER_BULLET_ITEM,
    DUPLICATE_BULLET_ITEM,
    BLANK_CODE,
    PLACEHOLDER_CODE,
    BLANK_CODE_LANGUAGE,
    EMPTY_COMPARISON_HEADERS,
    BLANK_COMPARISON_HEADER,
    DUPLICATE_COMPARISON_HEADER,
    EMPTY_COMPARISON_ROWS,
    COMPARISON_COLUMN_COUNT_MISMATCH,
    BLANK_COMPARISON_CELL,
    PLACEHOLDER_COMPARISON_CELL,
    BLANK_CALLOUT_TEXT,
    PLACEHOLDER_CALLOUT_TEXT,

    NO_SOURCES,
    BLANK_SOURCE_TITLE,
    PLACEHOLDER_SOURCE_TITLE,
    BLANK_SOURCE_URL,
    INVALID_SOURCE_URL,
    PLACEHOLDER_SOURCE_URL,
}
