package org.artkachenko.kmp_learning_app.curriculum.content

internal val androidPlatformQuestions = listOf(
    question(
        id = "android_process_model_001",
        topicId = "android_platform",
        subtopicId = "android_process_model",
        text = "Why should an Android app not rely on regular in-memory singletons to preserve user progress after the app is backgrounded?",
        correctAnswerIds = listOf("android_process_model_001_b"),
        explanation = "In-memory objects exist only inside the current app process. Android can kill a background process to reclaim resources, so user progress that must survive process death belongs in saved state or persistent storage.",
        sources = listOf(androidProcessesThreadsSource, androidSaveUiStateSource),
        answers = listOf(
            answer("android_process_model_001_a", "Because Android recreates every singleton on each Activity rotation even when the process remains alive."),
            answer("android_process_model_001_b", "Because the app process can be killed while backgrounded, clearing ordinary process memory."),
            answer("android_process_model_001_c", "Because singleton objects are stored in the manifest and cannot hold runtime data."),
            answer("android_process_model_001_d", "Because Kotlin object declarations are automatically persisted only on Android API 26 and lower."),
        ),
    ),
    question(
        id = "android_components_001",
        topicId = "android_platform",
        subtopicId = "android_components",
        text = "Which Android component is designed to expose a structured interface for sharing app-managed data with other apps?",
        correctAnswerIds = listOf("android_components_001_c"),
        explanation = "A ContentProvider presents data through a standard provider interface. Activities own UI, services perform background work, and broadcast receivers react to broadcast events.",
        sources = listOf(androidAppFundamentalsSource),
        answers = listOf(
            answer("android_components_001_a", "Activity"),
            answer("android_components_001_b", "Service"),
            answer("android_components_001_c", "ContentProvider"),
            answer("android_components_001_d", "BroadcastReceiver"),
        ),
    ),
    question(
        id = "android_context_001",
        topicId = "android_platform",
        subtopicId = "android_context",
        text = "A long-lived repository needs a Context only to access application resources. Which Context is safest to retain?",
        correctAnswerIds = listOf("android_context_001_b"),
        explanation = "A long-lived object should not retain an Activity context because that can leak the Activity. The application context is tied to the process and is appropriate for app-wide resource access.",
        sources = listOf(androidAppFundamentalsSource),
        answers = listOf(
            answer("android_context_001_a", "The current Activity context, because it always updates after configuration changes."),
            answer("android_context_001_b", "The application context, because it is not tied to a specific Activity instance."),
            answer("android_context_001_c", "A View context, because Views outlive their Activity by default."),
            answer("android_context_001_d", "Any Context, because all Context implementations have the same lifecycle."),
        ),
    ),
    question(
        id = "android_intents_001",
        topicId = "android_platform",
        subtopicId = "android_intents",
        text = "What is the main difference between an explicit Intent and an implicit Intent?",
        correctAnswerIds = listOf("android_intents_001_a"),
        explanation = "An explicit Intent identifies the target component directly. An implicit Intent describes an action or data so the system can resolve a matching component.",
        sources = listOf(androidAppFundamentalsSource),
        answers = listOf(
            answer("android_intents_001_a", "An explicit Intent names a target component; an implicit Intent describes an action to resolve."),
            answer("android_intents_001_b", "An explicit Intent can only start services; an implicit Intent can only start activities."),
            answer("android_intents_001_c", "An explicit Intent crosses process boundaries; an implicit Intent never can."),
            answer("android_intents_001_d", "An explicit Intent requires a PendingIntent; an implicit Intent cannot use one."),
        ),
    ),
    question(
        id = "android_main_thread_001",
        topicId = "android_platform",
        subtopicId = "android_main_thread",
        text = "Why should expensive disk or network work not run directly on Android's main thread?",
        correctAnswerIds = listOf("android_main_thread_001_c"),
        explanation = "The main thread processes UI work and input events. Blocking it with expensive operations can freeze rendering and input handling, leading to jank or ANRs.",
        sources = listOf(androidProcessesThreadsSource, androidPerformanceSource),
        answers = listOf(
            answer("android_main_thread_001_a", "Because the main thread cannot allocate memory."),
            answer("android_main_thread_001_b", "Because only background threads can access Kotlin suspend functions."),
            answer("android_main_thread_001_c", "Because blocking the main thread prevents timely UI rendering and input processing."),
            answer("android_main_thread_001_d", "Because Android automatically kills any app that opens a file on the main thread."),
        ),
    ),
    question(
        id = "android_resources_001",
        topicId = "android_platform",
        subtopicId = "android_resources",
        text = "What is the purpose of Android resource qualifiers such as layout-land or values-night?",
        correctAnswerIds = listOf("android_resources_001_d"),
        explanation = "Resource qualifiers let Android select alternative resources for the current device configuration, such as orientation, locale, density, or night mode.",
        sources = listOf(androidAppFundamentalsSource),
        answers = listOf(
            answer("android_resources_001_a", "They make resources private to a single Activity."),
            answer("android_resources_001_b", "They generate Kotlin constants for dependency injection."),
            answer("android_resources_001_c", "They disable configuration changes for matching screens."),
            answer("android_resources_001_d", "They provide alternative resources that Android selects for the current configuration."),
        ),
    ),
)

