package org.artkachenko.kmp_learning_app.curriculum.content

internal val androidUiQuestions = listOf(
    question(
        id = "views_fundamentals_001",
        topicId = "android_ui",
        subtopicId = "views_fundamentals",
        text = "In the classic Android View system, what is the role of a ViewGroup?",
        correctAnswerIds = listOf("views_fundamentals_001_b"),
        explanation = "A ViewGroup is a View that can contain child Views and is responsible for measuring and laying them out according to its layout rules.",
        sources = listOf(androidAppFundamentalsSource),
        answers = listOf(
            answer("views_fundamentals_001_a", "It stores app-wide singleton state for every screen."),
            answer("views_fundamentals_001_b", "It contains child Views and participates in measuring and laying them out."),
            answer("views_fundamentals_001_c", "It replaces the Activity lifecycle for UI code."),
            answer("views_fundamentals_001_d", "It is a resource qualifier for tablet layouts."),
        ),
    ),
    question(
        id = "view_rendering_001",
        topicId = "android_ui",
        subtopicId = "view_rendering",
        text = "What is the high-level order of work in the classic Android View rendering pipeline?",
        correctAnswerIds = listOf("view_rendering_001_a"),
        explanation = "The View system first measures sizes, then lays out positions, then draws. Custom Views must respect this separation to render correctly.",
        sources = listOf(androidAppFundamentalsSource),
        answers = listOf(
            answer("view_rendering_001_a", "Measure, layout, then draw."),
            answer("view_rendering_001_b", "Draw, layout, then measure."),
            answer("view_rendering_001_c", "Inflate, serialize, then persist."),
            answer("view_rendering_001_d", "Compose, remember, then dispose."),
        ),
    ),
    question(
        id = "recyclerview_001",
        topicId = "android_ui",
        subtopicId = "recyclerview",
        text = "Why does RecyclerView rely on ViewHolder reuse for large lists?",
        correctAnswerIds = listOf("recyclerview_001_d"),
        explanation = "RecyclerView reuses item Views through ViewHolders so scrolling large datasets does not require inflating and allocating a new View hierarchy for every item that appears.",
        sources = listOf(recyclerViewSource, androidPerformanceSource),
        answers = listOf(
            answer("recyclerview_001_a", "To make every list item share the same click listener identity."),
            answer("recyclerview_001_b", "To persist each row automatically across process death."),
            answer("recyclerview_001_c", "To prevent the adapter from ever receiving data changes."),
            answer("recyclerview_001_d", "To reduce repeated View inflation and allocation while scrolling."),
        ),
    ),
    question(
        id = "compose_state_001",
        topicId = "android_ui",
        subtopicId = "compose_state",
        text = "Why should Compose UI be driven by observable state rather than directly mutating emitted UI nodes?",
        correctAnswerIds = listOf("compose_state_001_b"),
        explanation = "Compose is declarative. UI is described from current state, and state changes cause recomposition with new arguments instead of mutating previously emitted UI objects directly.",
        sources = listOf(composeStateSource),
        answers = listOf(
            answer("compose_state_001_a", "Because Compose disables all mutable variables."),
            answer("compose_state_001_b", "Because composables describe UI from state and are called again when observed state changes."),
            answer("compose_state_001_c", "Because state objects are automatically written to Room."),
            answer("compose_state_001_d", "Because recomposition happens only once per Activity lifetime."),
        ),
    ),
    question(
        id = "compose_recomposition_001",
        topicId = "android_ui",
        subtopicId = "compose_recomposition",
        text = "What can cause a composable that reads Compose state to recompose?",
        correctAnswerIds = listOf("compose_recomposition_001_c"),
        explanation = "When a composable reads observable Compose state, changes to that state can invalidate the relevant composition and cause Compose to call the composable again with updated values.",
        sources = listOf(composeStateSource),
        answers = listOf(
            answer("compose_recomposition_001_a", "Only Activity recreation can cause recomposition."),
            answer("compose_recomposition_001_b", "Only explicit calls to invalidate() on a View can cause recomposition."),
            answer("compose_recomposition_001_c", "A change to observable state read by that composable."),
            answer("compose_recomposition_001_d", "Only a Gradle rebuild can cause recomposition."),
        ),
    ),
    question(
        id = "compose_state_hoisting_001",
        topicId = "android_ui",
        subtopicId = "compose_state_hoisting",
        text = "What is the usual goal of state hoisting in Compose?",
        correctAnswerIds = listOf("compose_state_hoisting_001_a"),
        explanation = "State hoisting moves state to an appropriate owner, often the lowest common ancestor that reads and writes it, which improves reuse, testability, and unidirectional data flow.",
        sources = listOf(composeStateHoistingSource, composeStateSource),
        answers = listOf(
            answer("compose_state_hoisting_001_a", "Move state to an appropriate owner and pass current value plus events down."),
            answer("compose_state_hoisting_001_b", "Store every UI value in a global singleton."),
            answer("compose_state_hoisting_001_c", "Prevent recomposition from ever happening."),
            answer("compose_state_hoisting_001_d", "Move state into XML resources so it can be localized."),
        ),
    ),
    question(
        id = "compose_side_effects_001",
        topicId = "android_ui",
        subtopicId = "compose_side_effects",
        text = "Which statements about Compose side-effect APIs are correct? Select all that apply.",
        correctAnswerIds = listOf("compose_side_effects_001_a", "compose_side_effects_001_c"),
        explanation = "Side-effect APIs run work that should be coordinated with composition lifecycle. LaunchedEffect launches a coroutine tied to composition keys, and DisposableEffect provides cleanup when its keys change or it leaves composition.",
        sources = listOf(composeSideEffectsSource),
        answers = listOf(
            answer("compose_side_effects_001_a", "LaunchedEffect launches a coroutine scoped to the composition for its key set."),
            answer("compose_side_effects_001_b", "Side-effect APIs are required for every Text composable."),
            answer("compose_side_effects_001_c", "DisposableEffect can clean up resources when the effect leaves composition or keys change."),
            answer("compose_side_effects_001_d", "rememberCoroutineScope automatically runs its block during every recomposition."),
        ),
    ),
    question(
        id = "compose_lazy_layouts_001",
        topicId = "android_ui",
        subtopicId = "compose_lazy_layouts",
        text = "Why are stable item keys important in Compose lazy lists when items can be inserted, removed, or reordered?",
        correctAnswerIds = listOf("compose_lazy_layouts_001_d"),
        explanation = "Stable keys let Compose keep item identity across dataset changes. That helps preserve item state and avoid treating moved items as unrelated new items.",
        sources = listOf(composeLazyListsSource),
        answers = listOf(
            answer("compose_lazy_layouts_001_a", "They make every row render on a background thread."),
            answer("compose_lazy_layouts_001_b", "They replace the need for state hoisting."),
            answer("compose_lazy_layouts_001_c", "They automatically persist list contents to disk."),
            answer("compose_lazy_layouts_001_d", "They preserve item identity across insertions, removals, and moves."),
        ),
    ),
    question(
        id = "compose_stability_001",
        topicId = "android_ui",
        subtopicId = "compose_stability",
        text = "How can unstable parameter types affect Compose performance?",
        correctAnswerIds = listOf("compose_stability_001_b"),
        explanation = "If Compose cannot know whether a parameter's value has changed safely, it may recompose more often instead of skipping work. Stable immutable models can improve skippability.",
        sources = listOf(composeStabilitySource),
        answers = listOf(
            answer("compose_stability_001_a", "They make the app fail to compile on Android only."),
            answer("compose_stability_001_b", "They can prevent Compose from skipping recomposition when inputs are effectively unchanged."),
            answer("compose_stability_001_c", "They force all state into SavedStateHandle."),
            answer("compose_stability_001_d", "They disable Material theming."),
        ),
    ),
    question(
        id = "compose_accessibility_001",
        topicId = "android_ui",
        subtopicId = "compose_accessibility",
        text = "What is the purpose of semantics information in Compose?",
        correctAnswerIds = listOf("compose_accessibility_001_c"),
        explanation = "Semantics describe UI meaning and actions to accessibility services and tests. They help non-visual users and automation understand the composable tree.",
        sources = listOf(composeAccessibilitySource, composeTestingSource),
        answers = listOf(
            answer("compose_accessibility_001_a", "To choose which Gradle variant builds the composable."),
            answer("compose_accessibility_001_b", "To replace all content descriptions with bitmap snapshots."),
            answer("compose_accessibility_001_c", "To expose UI meaning and actions to accessibility services and testing APIs."),
            answer("compose_accessibility_001_d", "To make composables persist automatically after process death."),
        ),
    ),
)
