package org.artkachenko.kmp_learning_app.curriculum.content

internal val architectureQuestions = listOf(
    question(
        id = "separation_of_concerns_001",
        topicId = "architecture",
        subtopicId = "separation_of_concerns",
        text = "Why is separation of concerns important in Android architecture?",
        correctAnswerIds = listOf("separation_of_concerns_001_c"),
        explanation = "Separating UI, state, data access, and business rules reduces coupling and makes each part easier to test, replace, and reason about.",
        sources = listOf(androidArchitectureSource),
        answers = listOf(
            answer("separation_of_concerns_001_a", "It guarantees that every screen needs only one class."),
            answer("separation_of_concerns_001_b", "It removes the need for tests."),
            answer("separation_of_concerns_001_c", "It keeps responsibilities focused so changes and tests affect smaller parts of the app."),
            answer("separation_of_concerns_001_d", "It requires all code to live in the data layer."),
        ),
    ),
    question(
        id = "unidirectional_data_flow_001",
        topicId = "architecture",
        subtopicId = "unidirectional_data_flow",
        text = "In unidirectional data flow, how do state and events usually move?",
        correctAnswerIds = listOf("unidirectional_data_flow_001_a"),
        explanation = "State flows from the owner toward the UI, and events flow back toward the owner that can decide how state changes.",
        sources = listOf(androidArchitectureSource, composeStateSource),
        answers = listOf(
            answer("unidirectional_data_flow_001_a", "State flows down to consumers, and events flow up to the state owner."),
            answer("unidirectional_data_flow_001_b", "Events and state both mutate every UI element directly."),
            answer("unidirectional_data_flow_001_c", "Only repositories are allowed to observe state."),
            answer("unidirectional_data_flow_001_d", "State must always be stored in global mutable objects."),
        ),
    ),
    question(
        id = "repository_pattern_001",
        topicId = "architecture",
        subtopicId = "repository_pattern",
        text = "What role does a repository usually play in Android app architecture?",
        correctAnswerIds = listOf("repository_pattern_001_b"),
        explanation = "A repository mediates app data operations and can coordinate local and remote data sources while exposing data to higher layers through a stable API.",
        sources = listOf(androidDataLayerSource),
        answers = listOf(
            answer("repository_pattern_001_a", "It renders composables directly."),
            answer("repository_pattern_001_b", "It coordinates access to one or more data sources behind a focused API."),
            answer("repository_pattern_001_c", "It replaces the Activity lifecycle."),
            answer("repository_pattern_001_d", "It must contain all navigation routes."),
        ),
    ),
    question(
        id = "single_source_of_truth_001",
        topicId = "architecture",
        subtopicId = "single_source_of_truth",
        text = "What does single source of truth mean for a piece of application data?",
        correctAnswerIds = listOf("single_source_of_truth_001_d"),
        explanation = "A single owner is responsible for changing and exposing that data. This avoids conflicting copies and makes updates traceable.",
        sources = listOf(androidArchitectureSource, androidDataLayerSource),
        answers = listOf(
            answer("single_source_of_truth_001_a", "Every screen keeps its own independent mutable copy."),
            answer("single_source_of_truth_001_b", "The network is always the source of truth, even offline."),
            answer("single_source_of_truth_001_c", "Only XML resources can hold the data."),
            answer("single_source_of_truth_001_d", "One owner is responsible for the data and exposes it to consumers."),
        ),
    ),
    question(
        id = "state_ownership_001",
        topicId = "architecture",
        subtopicId = "state_ownership",
        text = "Why should UI state have a clear owner?",
        correctAnswerIds = listOf("state_ownership_001_a"),
        explanation = "A clear owner controls mutation and exposes observable state, reducing accidental conflicting updates from multiple parts of the UI.",
        sources = listOf(androidArchitectureSource, composeStateHoistingSource),
        answers = listOf(
            answer("state_ownership_001_a", "So state changes have one responsible place and can be exposed predictably."),
            answer("state_ownership_001_b", "So every child composable can mutate the same backing field."),
            answer("state_ownership_001_c", "So state can avoid lifecycle concerns entirely."),
            answer("state_ownership_001_d", "So state never needs to be tested."),
        ),
    ),
    question(
        id = "dependency_direction_001",
        topicId = "architecture",
        subtopicId = "dependency_direction",
        text = "What problem does dependency inversion help solve between domain logic and data implementations?",
        correctAnswerIds = listOf("dependency_direction_001_c"),
        explanation = "Dependency inversion lets higher-level policy depend on abstractions instead of concrete lower-level details, making implementations replaceable and tests easier.",
        sources = listOf(androidArchitectureSource),
        answers = listOf(
            answer("dependency_direction_001_a", "It forces domain code to import every database class."),
            answer("dependency_direction_001_b", "It removes all runtime dependencies from the app."),
            answer("dependency_direction_001_c", "It keeps higher-level logic from depending directly on concrete implementation details."),
            answer("dependency_direction_001_d", "It makes networking run faster by default."),
        ),
    ),
    question(
        id = "architecture_tradeoffs_001",
        topicId = "architecture",
        subtopicId = "architecture_tradeoffs",
        text = "When is adding a use-case layer most defensible in an Android feature?",
        correctAnswerIds = listOf("architecture_tradeoffs_001_b"),
        explanation = "A use-case layer earns its place when it centralizes meaningful reusable business rules or coordinates multiple dependencies. Adding one for trivial pass-through calls can create needless indirection.",
        sources = listOf(androidArchitectureSource),
        answers = listOf(
            answer("architecture_tradeoffs_001_a", "Always, even when it only forwards one repository call unchanged."),
            answer("architecture_tradeoffs_001_b", "When it contains meaningful business rules or orchestration that would otherwise be duplicated or misplaced."),
            answer("architecture_tradeoffs_001_c", "Only when the UI is XML instead of Compose."),
            answer("architecture_tradeoffs_001_d", "Never, because repositories must contain all business rules."),
        ),
    ),
)

