package org.artkachenko.kmp_learning_app.curriculum.content

internal val asyncReactiveQuestions = listOf(
    question(
        id = "coroutine_fundamentals_001",
        topicId = "async_reactive",
        subtopicId = "coroutine_fundamentals",
        text = "What does a suspend function indicate in Kotlin?",
        correctAnswerIds = listOf("coroutine_fundamentals_001_b"),
        explanation = "A suspend function can suspend execution without blocking the underlying thread and later resume. It still needs to be called from another suspend function or coroutine.",
        sources = listOf(coroutinesBasicsSource),
        answers = listOf(
            answer("coroutine_fundamentals_001_a", "It always runs on a new operating-system thread."),
            answer("coroutine_fundamentals_001_b", "It can suspend without blocking the thread and resume later."),
            answer("coroutine_fundamentals_001_c", "It is automatically retried after exceptions."),
            answer("coroutine_fundamentals_001_d", "It can be called from any regular function with no coroutine context."),
        ),
    ),
    question(
        id = "coroutine_builders_001",
        topicId = "async_reactive",
        subtopicId = "coroutine_builders",
        text = "When is async more appropriate than launch?",
        correctAnswerIds = listOf("coroutine_builders_001_c"),
        explanation = "async returns a Deferred for a result that can be awaited. launch is better for fire-and-forget child work that does not directly produce a value.",
        sources = listOf(coroutinesBasicsSource),
        answers = listOf(
            answer("coroutine_builders_001_a", "When the coroutine must ignore all cancellation."),
            answer("coroutine_builders_001_b", "When the coroutine should never have a parent Job."),
            answer("coroutine_builders_001_c", "When the caller needs a result represented by Deferred."),
            answer("coroutine_builders_001_d", "When the code must run synchronously on the caller thread."),
        ),
    ),
    question(
        id = "structured_concurrency_001",
        topicId = "async_reactive",
        subtopicId = "structured_concurrency",
        text = "What problem does structured concurrency address?",
        correctAnswerIds = listOf("structured_concurrency_001_a"),
        explanation = "Structured concurrency ties child coroutines to a parent scope so lifetimes, cancellation, and failure are managed predictably rather than leaving work running unowned.",
        sources = listOf(coroutinesBasicsSource),
        answers = listOf(
            answer("structured_concurrency_001_a", "It keeps coroutine lifetimes tied to explicit scopes and parent-child relationships."),
            answer("structured_concurrency_001_b", "It guarantees every coroutine runs on Dispatchers.Main."),
            answer("structured_concurrency_001_c", "It disables exception propagation between child coroutines."),
            answer("structured_concurrency_001_d", "It converts every Flow into LiveData."),
        ),
    ),
    question(
        id = "coroutine_cancellation_001",
        topicId = "async_reactive",
        subtopicId = "coroutine_cancellation",
        text = "Why should long-running coroutine loops check for cancellation or call cancellable suspending functions?",
        correctAnswerIds = listOf("coroutine_cancellation_001_d"),
        explanation = "Coroutine cancellation is cooperative. Code that never suspends and never checks cancellation may keep running even after its Job is cancelled.",
        sources = listOf(coroutinesCancellationSource),
        answers = listOf(
            answer("coroutine_cancellation_001_a", "Because cancellation always interrupts the CPU instruction currently running."),
            answer("coroutine_cancellation_001_b", "Because cancelled coroutines are automatically restarted."),
            answer("coroutine_cancellation_001_c", "Because cancellation only works for network requests."),
            answer("coroutine_cancellation_001_d", "Because cancellation is cooperative and busy code must reach a cancellation check."),
        ),
    ),
    question(
        id = "coroutine_exceptions_001",
        topicId = "async_reactive",
        subtopicId = "coroutine_exceptions",
        text = "How does a regular Job parent usually react when one child coroutine fails with an uncaught exception?",
        correctAnswerIds = listOf("coroutine_exceptions_001_b"),
        explanation = "In regular structured concurrency, an uncaught child failure cancels the parent, which then cancels its other children. Supervision changes that behavior.",
        sources = listOf(coroutinesExceptionsSource),
        answers = listOf(
            answer("coroutine_exceptions_001_a", "It ignores the failure and lets all children continue."),
            answer("coroutine_exceptions_001_b", "It is cancelled, and sibling children are cancelled as a consequence."),
            answer("coroutine_exceptions_001_c", "It retries the failed child automatically."),
            answer("coroutine_exceptions_001_d", "It converts the exception into null."),
        ),
    ),
    question(
        id = "coroutine_context_switching_001",
        topicId = "async_reactive",
        subtopicId = "coroutine_context_switching",
        text = "What is withContext commonly used for in Android coroutine code?",
        correctAnswerIds = listOf("coroutine_context_switching_001_c"),
        explanation = "withContext runs a block in a different coroutine context, commonly switching blocking IO work to an IO dispatcher while preserving structured execution.",
        sources = listOf(coroutinesContextSource),
        answers = listOf(
            answer("coroutine_context_switching_001_a", "Creating an unstructured global coroutine."),
            answer("coroutine_context_switching_001_b", "Launching two independent coroutines and returning immediately."),
            answer("coroutine_context_switching_001_c", "Switching execution context for a scoped block of suspending work."),
            answer("coroutine_context_switching_001_d", "Persisting coroutine state after process death."),
        ),
    ),
    question(
        id = "flow_fundamentals_001",
        topicId = "async_reactive",
        subtopicId = "flow_fundamentals",
        text = "What makes a basic Kotlin Flow cold?",
        correctAnswerIds = listOf("flow_fundamentals_001_a"),
        explanation = "A cold Flow does not run its producer until it is collected. Each collection can start the flow pipeline again.",
        sources = listOf(flowSource),
        answers = listOf(
            answer("flow_fundamentals_001_a", "Its producer starts when the flow is collected."),
            answer("flow_fundamentals_001_b", "It always stores the latest value in memory."),
            answer("flow_fundamentals_001_c", "It emits only on Android's main thread."),
            answer("flow_fundamentals_001_d", "It can have only one operator."),
        ),
    ),
    question(
        id = "flow_context_001",
        topicId = "async_reactive",
        subtopicId = "flow_context",
        text = "What does flowOn affect in a Kotlin Flow pipeline?",
        correctAnswerIds = listOf("flow_context_001_d"),
        explanation = "flowOn changes the context of upstream flow operations. It does not change the collector's coroutine context downstream.",
        sources = listOf(flowSource),
        answers = listOf(
            answer("flow_context_001_a", "Only the terminal collector block."),
            answer("flow_context_001_b", "Every coroutine in the application process."),
            answer("flow_context_001_c", "Only exception handlers attached to the Activity."),
            answer("flow_context_001_d", "The upstream part of the flow before the flowOn operator."),
        ),
    ),
    question(
        id = "stateflow_001",
        topicId = "async_reactive",
        subtopicId = "stateflow",
        text = "When is StateFlow a good fit for exposing UI state from a ViewModel?",
        correctAnswerIds = listOf("stateflow_001_b"),
        explanation = "StateFlow represents observable state with a current value. That matches screen UI state that Compose or other UI layers can observe.",
        sources = listOf(stateFlowSource, composeStateHoistingSource),
        answers = listOf(
            answer("stateflow_001_a", "When each collector must receive a different one-time event."),
            answer("stateflow_001_b", "When the UI needs the latest state value and updates when it changes."),
            answer("stateflow_001_c", "When the state must be stored in SQLite automatically."),
            answer("stateflow_001_d", "When there should be no initial value."),
        ),
    ),
    question(
        id = "sharedflow_001",
        topicId = "async_reactive",
        subtopicId = "sharedflow",
        text = "Which statements about SharedFlow are correct? Select all that apply.",
        correctAnswerIds = listOf("sharedflow_001_a", "sharedflow_001_d"),
        explanation = "SharedFlow is a hot flow that can broadcast emissions to active collectors. Depending on replay configuration, it may or may not replay past values to new collectors.",
        sources = listOf(stateFlowSource),
        answers = listOf(
            answer("sharedflow_001_a", "It is a hot flow."),
            answer("sharedflow_001_b", "It must always have exactly one current value."),
            answer("sharedflow_001_c", "It is collected only once globally and then completes forever."),
            answer("sharedflow_001_d", "Its replay behavior is configurable."),
        ),
    ),
)

