package org.artkachenko.kmp_learning_app.curriculum.content

import org.artkachenko.kmp_learning_app.curriculum.Subtopic

internal val initialSubtopics = listOf(
    st("android_process_model", "android_platform", "Application and process model"),
    st("android_components", "android_platform", "Android application components"),
    st("android_context", "android_platform", "Context"),
    st("android_intents", "android_platform", "Intents"),
    st("android_manifest", "android_platform", "Manifest and application configuration"),
    st("android_resources", "android_platform", "Android resources and qualifiers"),
    st("android_main_thread", "android_platform", "Main thread, Looper, and Handler fundamentals"),
    st("android_ipc", "android_platform", "Android IPC fundamentals"),
    st("activity_lifecycle", "lifecycle_navigation", "Activity lifecycle"),
    st("fragment_lifecycle", "lifecycle_navigation", "Fragment and Fragment view lifecycle"),
    st("configuration_changes", "lifecycle_navigation", "Configuration changes"),
    st("process_death", "lifecycle_navigation", "Process death and recreation"),
    st("viewmodel_lifecycle", "lifecycle_navigation", "ViewModel lifecycle"),
    st("saved_state", "lifecycle_navigation", "Saved-state mechanisms"),
    st("lifecycle_aware_apis", "lifecycle_navigation", "Lifecycle-aware APIs"),
    st("navigation_fundamentals", "lifecycle_navigation", "Navigation and back-stack fundamentals"),
    st("navigation_2_vs_3", "lifecycle_navigation", "Navigation 2 vs Navigation 3"),
    st("deep_links", "lifecycle_navigation", "Deep links"),
    st("back_handling", "lifecycle_navigation", "Back handling and predictive back"),
    st("views_fundamentals", "android_ui", "View and ViewGroup fundamentals"),
    st("xml_layouts", "android_ui", "XML layouts"),
    st("view_rendering", "android_ui", "Measure, layout, and draw"),
    st("recyclerview", "android_ui", "RecyclerView"),
    st("custom_views", "android_ui", "Custom Views"),
    st("view_events", "android_ui", "View event handling"),
    st("view_binding", "android_ui", "ViewBinding and DataBinding awareness"),
    st("compose_fundamentals", "android_ui", "Compose fundamentals"),
    st("compose_recomposition", "android_ui", "Composition and recomposition"),
    st("compose_state", "android_ui", "Compose state"),
    st("compose_state_hoisting", "android_ui", "State hoisting"),
    st("compose_udf", "android_ui", "Unidirectional data flow in Compose"),
    st("compose_side_effects", "android_ui", "Compose side-effect APIs"),
    st("compose_derived_state", "android_ui", "derivedStateOf and derived state"),
    st("compose_snapshot_system", "android_ui", "Compose snapshot-system fundamentals"),
    st("compose_layouts_modifiers", "android_ui", "Layouts and Modifiers"),
    st("compose_lazy_layouts", "android_ui", "Lazy layouts"),
    st("compose_identity_keys", "android_ui", "Identity and keys"),
    st("compose_stability", "android_ui", "Stability and skippability"),
    st("composition_local", "android_ui", "CompositionLocal"),
    st("compose_theming", "android_ui", "Material 3 and theming"),
    st("compose_accessibility", "android_ui", "Semantics and accessibility"),
    st("compose_previews", "android_ui", "Compose previews"),
    st("views_compose_interop", "android_ui", "Views and Compose interoperability"),
    st("kotlin_variables", "kotlin_language", "val, var, and basic declarations"),
    st("kotlin_nullability", "kotlin_language", "Nullability"),
    st("kotlin_functions", "kotlin_language", "Functions and arguments"),
    st("kotlin_extension_functions", "kotlin_language", "Extension functions"),
    st("kotlin_classes", "kotlin_language", "Kotlin classes"),
    st("kotlin_data_classes", "kotlin_language", "Data classes"),
    st("kotlin_objects", "kotlin_language", "object and companion object"),
    st("kotlin_sealed_types", "kotlin_language", "Sealed classes and interfaces"),
    st("kotlin_interfaces_inheritance", "kotlin_language", "Interfaces and inheritance"),
    st("kotlin_visibility", "kotlin_language", "Visibility modifiers"),
    st("kotlin_properties", "kotlin_language", "Properties, accessors, and backing fields"),
    st("kotlin_delegation", "kotlin_language", "Delegation and delegated properties"),
    st("kotlin_generics", "kotlin_language", "Generics and variance"),
    st("kotlin_lambdas", "kotlin_language", "Lambdas and higher-order functions"),
    st("kotlin_inline_functions", "kotlin_language", "inline, noinline, and crossinline"),
    st("kotlin_reified_types", "kotlin_language", "Reified type parameters"),
    st("kotlin_collections", "kotlin_language", "Collections"),
    st("kotlin_sequences", "kotlin_language", "Sequences and lazy collection processing"),
    st("kotlin_equality", "kotlin_language", "Structural vs referential equality"),
    st("kotlin_exceptions", "kotlin_language", "Exception handling"),
    st("kotlin_scope_functions", "kotlin_language", "let/run/apply/also/with"),
    st("kotlin_java_interop", "kotlin_language", "Java interoperability"),
    st("jvm_fundamentals", "kotlin_language", "JVM fundamentals relevant to Android"),
    st("coroutine_fundamentals", "async_reactive", "Coroutine and suspend fundamentals"),
    st("coroutine_builders", "async_reactive", "launch and async"),
    st("coroutine_scope", "async_reactive", "CoroutineScope"),
    st("coroutine_context", "async_reactive", "CoroutineContext"),
    st("coroutine_dispatchers", "async_reactive", "Dispatchers"),
    st("coroutine_jobs", "async_reactive", "Job and parent-child relationships"),
    st("structured_concurrency", "async_reactive", "Structured concurrency"),
    st("coroutine_cancellation", "async_reactive", "Cancellation"),
    st("coroutine_exceptions", "async_reactive", "Exception propagation and handling"),
    st("coroutine_supervision", "async_reactive", "SupervisorJob and supervisorScope"),
    st("coroutine_context_switching", "async_reactive", "withContext"),
    st("coroutine_parallelism", "async_reactive", "Concurrency and async/await"),
    st("lifecycle_coroutines", "async_reactive", "Lifecycle-aware coroutine scopes"),
    st("flow_fundamentals", "async_reactive", "Flow fundamentals"),
    st("flow_operators", "async_reactive", "Flow operators"),
    st("flow_collection", "async_reactive", "Flow collection"),
    st("flow_errors", "async_reactive", "Flow exception handling"),
    st("flow_context", "async_reactive", "flowOn and execution context"),
    st("flow_buffering", "async_reactive", "Buffering and conflation"),
    st("stateflow", "async_reactive", "StateFlow"),
    st("sharedflow", "async_reactive", "SharedFlow"),
    st("hot_vs_cold_streams", "async_reactive", "Hot vs cold streams"),
    st("flow_sharing", "async_reactive", "stateIn, shareIn, and sharing policies"),
    st("livedata", "async_reactive", "LiveData"),
    st("rxjava_fundamentals", "async_reactive", "RxJava/RxKotlin fundamentals"),
    st("flow_vs_rxjava", "async_reactive", "Flow vs RxJava"),
    st("separation_of_concerns", "architecture", "Separation of concerns"),
    st("layered_architecture", "architecture", "Layered architecture"),
    st("mvc", "architecture", "MVC"),
    st("mvp", "architecture", "MVP"),
    st("mvvm", "architecture", "MVVM"),
    st("mvi", "architecture", "MVI"),
    st("mvvm_vs_mvi", "architecture", "MVVM vs MVI"),
    st("unidirectional_data_flow", "architecture", "Unidirectional data flow"),
    st("repository_pattern", "architecture", "Repository pattern"),
    st("use_cases", "architecture", "Use cases and when to introduce them"),
    st("single_source_of_truth", "architecture", "Single source of truth"),
    st("state_ownership", "architecture", "State ownership"),
    st("clean_architecture", "architecture", "Clean Architecture"),
    st("solid", "architecture", "SOLID principles"),
    st("dependency_direction", "architecture", "Dependency direction and inversion"),
    st("interface_boundaries", "architecture", "Interface boundaries"),
    st("error_modeling", "architecture", "Error representation/modeling"),
    st("architecture_tradeoffs", "architecture", "Architecture trade-offs and avoiding over-engineering"),
    st("di_fundamentals", "dependency_injection", "Dependency injection fundamentals"),
    st("manual_di", "dependency_injection", "Manual dependency injection"),
    st("constructor_injection", "dependency_injection", "Constructor injection"),
    st("composition_root", "dependency_injection", "Composition root"),
    st("dependency_graphs", "dependency_injection", "Dependency graphs"),
    st("di_scopes", "dependency_injection", "Scopes and lifetimes"),
    st("service_locator_vs_di", "dependency_injection", "Service locator vs dependency injection"),
    st("dagger_fundamentals", "dependency_injection", "Dagger fundamentals"),
    st("dagger_modules", "dependency_injection", "Dagger modules"),
    st("dagger_bindings", "dependency_injection", "@Provides and @Binds"),
    st("dagger_components", "dependency_injection", "Components and subcomponents"),
    st("dagger_scopes", "dependency_injection", "Dagger scopes"),
    st("dagger_qualifiers", "dependency_injection", "Qualifiers"),
    st("dagger_multibindings", "dependency_injection", "Multibindings"),
    st("hilt_fundamentals", "dependency_injection", "Hilt fundamentals"),
    st("hilt_components", "dependency_injection", "Hilt components and lifecycle scopes"),
    st("hilt_viewmodels", "dependency_injection", "Hilt ViewModels"),
    st("hilt_modules", "dependency_injection", "Hilt modules and InstallIn"),
    st("hilt_vs_dagger", "dependency_injection", "Hilt vs raw Dagger"),
    st("koin_fundamentals", "dependency_injection", "Koin fundamentals"),
    st("koin_definitions", "dependency_injection", "single/factory definitions"),
    st("koin_scopes", "dependency_injection", "Koin scopes"),
    st("koin_viewmodels", "dependency_injection", "Koin ViewModel integration"),
    st("koin_multiplatform", "dependency_injection", "Koin and Kotlin Multiplatform"),
    st("di_framework_tradeoffs", "dependency_injection", "DI framework trade-offs"),
    st("storage_selection", "local_data", "Choosing a storage mechanism"),
    st("shared_preferences", "local_data", "SharedPreferences"),
    st("datastore", "local_data", "DataStore"),
    st("datastore_vs_sharedpreferences", "local_data", "DataStore vs SharedPreferences"),
    st("file_storage", "local_data", "File storage"),
    st("sqlite_fundamentals", "local_data", "SQLite and relational-database fundamentals"),
    st("room_fundamentals", "local_data", "Room fundamentals"),
    st("room_entities", "local_data", "Room entities"),
    st("room_dao", "local_data", "Room DAOs and queries"),
    st("room_relationships", "local_data", "Room relationships"),
    st("room_type_converters", "local_data", "Type converters"),
    st("room_transactions", "local_data", "Transactions"),
    st("room_migrations", "local_data", "Room migrations"),
    st("room_flow", "local_data", "Room and Flow"),
    st("caching", "local_data", "Caching"),
    st("offline_first", "local_data", "Offline-first architecture"),
    st("cache_invalidation", "local_data", "Cache invalidation"),
    st("schema_migrations", "local_data", "Schema/version migration concepts"),
    st("room_vs_sqldelight", "local_data", "Room vs SQLDelight"),
    st("http_fundamentals", "networking", "HTTP fundamentals"),
    st("http_methods", "networking", "HTTP methods"),
    st("http_status_codes", "networking", "HTTP status codes"),
    st("rest", "networking", "REST concepts"),
    st("http_idempotency", "networking", "Idempotency"),
    st("pagination", "networking", "Pagination"),
    st("network_timeouts", "networking", "Timeouts"),
    st("network_retries", "networking", "Retries and backoff"),
    st("tls_https", "networking", "HTTPS/TLS fundamentals"),
    st("okhttp", "networking", "OkHttp"),
    st("okhttp_interceptors", "networking", "OkHttp interceptors"),
    st("retrofit", "networking", "Retrofit"),
    st("retrofit_coroutines", "networking", "Retrofit and coroutines"),
    st("network_error_handling", "networking", "Network error handling"),
    st("ktor_client", "networking", "Ktor Client"),
    st("retrofit_vs_ktor", "networking", "Retrofit vs Ktor"),
    st("json_fundamentals", "networking", "JSON fundamentals"),
    st("gson", "networking", "Gson"),
    st("moshi", "networking", "Moshi"),
    st("kotlinx_serialization", "networking", "kotlinx.serialization"),
    st("serialization_strategies", "networking", "Reflection vs generated/compiler-assisted serialization"),
    st("custom_serialization", "networking", "Custom serializers/adapters"),
    st("json_compatibility", "networking", "Missing, unknown, nullable, and default JSON fields"),
    st("network_caching", "networking", "HTTP/network caching"),
    st("websockets", "networking", "WebSockets"),
    st("streaming", "networking", "Streaming concepts"),
    st("authentication_tokens", "networking", "Authentication tokens"),
    st("token_refresh", "networking", "Token refresh flows"),
    st("background_execution", "background_work", "Android background execution model"),
    st("services", "background_work", "Services"),
    st("foreground_services", "background_work", "Foreground services"),
    st("bound_services", "background_work", "Bound services"),
    st("workmanager", "background_work", "WorkManager fundamentals"),
    st("workmanager_constraints", "background_work", "WorkManager constraints"),
    st("workmanager_chaining", "background_work", "Work chaining"),
    st("workmanager_retries", "background_work", "WorkManager retries"),
    st("service_vs_workmanager", "background_work", "Service vs WorkManager"),
    st("alarmmanager", "background_work", "AlarmManager"),
    st("exact_alarms", "background_work", "Exact alarms"),
    st("doze", "background_work", "Doze"),
    st("app_standby", "background_work", "App Standby"),
    st("battery_restrictions", "background_work", "Battery restrictions"),
    st("background_limits", "background_work", "Background execution limits"),
    st("background_process_death", "background_work", "Process-death implications"),
    st("boot_restart_work", "background_work", "Work across reboot/restart"),
    st("long_running_work", "background_work", "Long-running work"),
    st("foreground_service_types", "background_work", "Foreground-service types and permissions"),
    st("background_api_selection", "background_work", "Choosing the appropriate background API"),
    st("notification_fundamentals", "notifications", "Android notification fundamentals"),
    st("notification_channels", "notifications", "Notification channels"),
    st("notification_importance", "notifications", "Notification importance"),
    st("notification_pending_intents", "notifications", "PendingIntent in notifications"),
    st("notification_actions", "notifications", "Notification actions"),
    st("notification_grouping", "notifications", "Notification grouping"),
    st("notification_permission", "notifications", "Runtime notification permission"),
    st("fcm_fundamentals", "notifications", "Firebase Cloud Messaging fundamentals"),
    st("fcm_tokens", "notifications", "FCM registration tokens"),
    st("fcm_notification_messages", "notifications", "Notification messages"),
    st("fcm_data_messages", "notifications", "Data messages"),
    st("fcm_app_state_behavior", "notifications", "Foreground/background behavior"),
    st("fcm_token_refresh", "notifications", "Token refresh"),
    st("fcm_message_handling", "notifications", "Message handling"),
    st("notification_deep_links", "notifications", "Deep linking from notifications"),
    st("push_delivery_constraints", "notifications", "Push delivery limitations"),
    st("fcm_priority", "notifications", "FCM message priority"),
    st("push_system_architecture", "notifications", "Backend-to-FCM-to-device architecture"),
    st("testing_strategy", "testing", "Test strategy"),
    st("unit_testing", "testing", "Unit tests"),
    st("integration_testing", "testing", "Integration tests"),
    st("ui_testing", "testing", "UI tests"),
    st("local_vs_instrumented_tests", "testing", "Local vs instrumented tests"),
    st("junit", "testing", "JUnit"),
    st("test_doubles", "testing", "Test doubles"),
    st("fakes_vs_mocks", "testing", "Fakes, mocks, and stubs"),
    st("viewmodel_testing", "testing", "ViewModel testing"),
    st("coroutine_testing", "testing", "Coroutine testing"),
    st("flow_testing", "testing", "Flow testing"),
    st("run_test", "testing", "runTest"),
    st("virtual_time", "testing", "Virtual time"),
    st("repository_testing", "testing", "Repository testing"),
    st("room_testing", "testing", "Room/database testing"),
    st("compose_ui_testing", "testing", "Compose UI testing"),
    st("espresso", "testing", "Espresso awareness"),
    st("test_di", "testing", "Dependency replacement/injection in tests"),
    st("test_determinism", "testing", "Deterministic tests"),
    st("architecture_for_testability", "testing", "Architecture for testability"),
    st("testing_boundaries", "testing", "What to test and where"),
    st("flaky_tests", "testing", "Flaky-test prevention/debugging"),
    st("android_memory_model", "performance", "Android/JVM memory fundamentals"),
    st("memory_leaks", "performance", "Memory leaks"),
    st("context_leaks", "performance", "Context leaks"),
    st("lifecycle_leaks", "performance", "Activity/Fragment/listener leaks"),
    st("coroutine_leaks", "performance", "Coroutine lifetime leaks"),
    st("garbage_collection", "performance", "Garbage collection fundamentals"),
    st("anr", "performance", "ANRs"),
    st("main_thread_performance", "performance", "Main-thread performance"),
    st("rendering_jank", "performance", "Rendering and jank"),
    st("startup_performance", "performance", "App startup"),
    st("lazy_initialization", "performance", "Lazy initialization"),
    st("recyclerview_performance", "performance", "RecyclerView performance"),
    st("compose_performance", "performance", "Compose performance"),
    st("compose_recomposition_performance", "performance", "Avoiding unnecessary recomposition"),
    st("android_profiler", "performance", "Android Studio profiling fundamentals"),
    st("cpu_profiling", "performance", "CPU profiling"),
    st("memory_profiling", "performance", "Memory profiling"),
    st("network_inspection", "performance", "Network inspection"),
    st("layout_inspector", "performance", "Layout Inspector / Compose inspection"),
    st("strictmode", "performance", "StrictMode"),
    st("r8", "performance", "R8"),
    st("baseline_profiles", "performance", "Baseline Profiles"),
    st("macrobenchmark", "performance", "Macrobenchmark awareness"),
    st("android_sandbox", "security", "Android application sandbox"),
    st("android_permissions", "security", "Permission model"),
    st("runtime_permissions", "security", "Runtime permissions"),
    st("permission_ux", "security", "Permission-request UX"),
    st("exported_components", "security", "Exported components"),
    st("intent_security", "security", "Intent security"),
    st("pending_intent_security", "security", "PendingIntent security"),
    st("content_provider_security", "security", "ContentProvider security"),
    st("secure_storage", "security", "Secure local storage"),
    st("android_keystore", "security", "Android Keystore"),
    st("encryption_fundamentals", "security", "Encryption fundamentals"),
    st("secret_management", "security", "API keys and secret management"),
    st("network_security", "security", "Network security"),
    st("certificate_pinning", "security", "Certificate pinning and trade-offs"),
    st("auth_token_security", "security", "Authentication-token security"),
    st("biometric_auth", "security", "Biometric authentication awareness"),
    st("webview_security", "security", "WebView security"),
    st("sensitive_logging", "security", "Sensitive-data logging"),
    st("compromised_devices", "security", "Rooted/compromised-device limitations"),
    st("privacy_principles", "security", "Privacy and data-minimization principles"),
    st("gradle_fundamentals", "build_delivery", "Gradle fundamentals"),
    st("gradle_wrapper", "build_delivery", "Gradle Wrapper"),
    st("gradle_plugins", "build_delivery", "Gradle plugins"),
    st("dependency_configurations", "build_delivery", "Dependency configurations"),
    st("version_catalogs", "build_delivery", "Version catalogs"),
    st("android_gradle_plugin", "build_delivery", "Android Gradle Plugin"),
    st("kotlin_gradle_plugin", "build_delivery", "Kotlin Gradle plugin"),
    st("build_variants", "build_delivery", "Build variants"),
    st("build_types", "build_delivery", "Build types"),
    st("product_flavors", "build_delivery", "Product flavors"),
    st("source_sets", "build_delivery", "Source sets"),
    st("dependency_resolution", "build_delivery", "Dependency resolution"),
    st("android_modules", "build_delivery", "Application/library modules"),
    st("feature_modularization", "build_delivery", "Feature modularization"),
    st("module_dependency_direction", "build_delivery", "Module dependency direction"),
    st("api_vs_implementation", "build_delivery", "api vs implementation"),
    st("modularization_tradeoffs", "build_delivery", "Benefits and costs of modularization"),
    st("apk_vs_aab", "build_delivery", "APK vs Android App Bundle"),
    st("app_signing", "build_delivery", "Application signing"),
    st("release_builds", "build_delivery", "Debug vs release"),
    st("code_shrinking", "build_delivery", "Code shrinking/obfuscation"),
    st("resource_shrinking", "build_delivery", "Resource shrinking"),
    st("app_versioning", "build_delivery", "versionCode/versionName"),
    st("ci_fundamentals", "build_delivery", "CI fundamentals"),
    st("cd_fundamentals", "build_delivery", "Delivery/release pipeline fundamentals"),
    st("requirements_analysis", "mobile_system_design", "Requirements clarification"),
    st("nonfunctional_requirements", "mobile_system_design", "Non-functional requirements"),
    st("system_decomposition", "mobile_system_design", "Client/system decomposition"),
    st("system_data_flow", "mobile_system_design", "Data flow"),
    st("local_remote_sources", "mobile_system_design", "Local vs remote sources of truth"),
    st("system_caching", "mobile_system_design", "Caching strategy"),
    st("offline_design", "mobile_system_design", "Offline behavior"),
    st("data_synchronization", "mobile_system_design", "Data synchronization"),
    st("conflict_resolution", "mobile_system_design", "Conflict resolution"),
    st("system_pagination", "mobile_system_design", "Pagination design"),
    st("system_retries", "mobile_system_design", "Error and retry design"),
    st("background_sync", "mobile_system_design", "Background synchronization"),
    st("push_driven_updates", "mobile_system_design", "Push-driven updates"),
    st("session_management", "mobile_system_design", "Authentication/session handling"),
    st("large_scale_modularization", "mobile_system_design", "Modularization at scale"),
    st("client_scalability", "mobile_system_design", "Client-code scalability"),
    st("mobile_resource_constraints", "mobile_system_design", "Battery/network/device constraints"),
    st("observability", "mobile_system_design", "Logging/observability considerations"),
    st("feature_flags", "mobile_system_design", "Feature flags"),
    st("backward_compatibility", "mobile_system_design", "Backward compatibility"),
    st("api_evolution", "mobile_system_design", "API evolution"),
    st("rollout_strategy", "mobile_system_design", "Rollout and migrations"),
    st("system_security", "mobile_system_design", "Security/privacy in system design"),
    st("system_testing_strategy", "mobile_system_design", "Testing strategy for designed systems"),
    st("kmp_fundamentals", "kmp", "Kotlin Multiplatform fundamentals"),
    st("kmp_targets", "kmp", "Targets"),
    st("kmp_source_sets", "kmp", "Source sets"),
    st("commonmain", "kmp", "commonMain"),
    st("kmp_dependency_hierarchy", "kmp", "Source-set/dependency hierarchy"),
    st("shared_vs_platform_code", "kmp", "What to share vs keep platform-specific"),
    st("expect_actual", "kmp", "expect/actual"),
    st("kmp_platform_apis", "kmp", "Accessing platform APIs"),
    st("kotlin_native", "kmp", "Kotlin/Native awareness"),
    st("kmp_architecture", "kmp", "KMP architecture"),
    st("shared_domain", "kmp", "Shared domain logic"),
    st("shared_data", "kmp", "Shared data layer"),
    st("shared_presentation", "kmp", "Shared presentation logic"),
    st("kmp_dependency_inversion", "kmp", "Cross-platform dependency inversion"),
    st("platform_implementations", "kmp", "Platform-specific implementations"),
    st("compose_multiplatform", "kmp", "Compose Multiplatform fundamentals"),
    st("compose_multiplatform_resources", "kmp", "Compose Multiplatform Resources"),
    st("kmp_lifecycle_viewmodel", "kmp", "Multiplatform Lifecycle/ViewModel"),
    st("kmp_navigation", "kmp", "Multiplatform navigation"),
    st("platform_ui_interop", "kmp", "Platform UI interoperability"),
    st("kmp_library_selection", "kmp", "Evaluating KMP library compatibility"),
    st("kotlinx_serialization_kmp", "kmp", "kotlinx.serialization in KMP"),
    st("ktor_kmp", "kmp", "Ktor in KMP"),
    st("room_kmp", "kmp", "Room KMP"),
    st("sqldelight", "kmp", "SQLDelight"),
    st("koin_kmp", "kmp", "Koin in KMP"),
    st("kmp_tradeoffs", "kmp", "Practical KMP trade-offs"),
)

private fun st(id: String, topicId: String, name: String) = Subtopic(
    id = id,
    topicId = topicId,
    name = name,
)

