package org.artkachenko.kmp_learning_app.curriculum.content

internal val kotlinLanguageQuestions = listOf(
    question(
        id = "kotlin_nullability_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_nullability",
        text = "What does Kotlin's type system express when a variable has nullable type String? instead of non-null type String?",
        correctAnswerIds = listOf("kotlin_nullability_001_b"),
        explanation = "A non-null String type cannot hold null without unsafe interop or explicit tricks. Nullable types are written with a question mark, such as String?.",
        sources = listOf(kotlinNullSafetySource),
        answers = listOf(
            answer("kotlin_nullability_001_a", "Both types can hold null; the difference is only documentation."),
            answer("kotlin_nullability_001_b", "String is non-null, while String? is nullable."),
            answer("kotlin_nullability_001_c", "String is nullable, while String? is non-null."),
            answer("kotlin_nullability_001_d", "Nullability is checked only at runtime on Android."),
        ),
    ),
    question(
        id = "kotlin_data_classes_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_data_classes",
        text = "What does a Kotlin data class primarily generate from properties declared in its primary constructor?",
        correctAnswerIds = listOf("kotlin_data_classes_001_c"),
        explanation = "Data classes generate value-oriented members such as equals(), hashCode(), toString(), componentN(), and copy() based on primary constructor properties.",
        sources = listOf(kotlinDataClassesSource),
        answers = listOf(
            answer("kotlin_data_classes_001_a", "Android Parcelable implementation for every property."),
            answer("kotlin_data_classes_001_b", "A Room table and DAO."),
            answer("kotlin_data_classes_001_c", "Value-oriented functions such as equals(), hashCode(), toString(), componentN(), and copy()."),
            answer("kotlin_data_classes_001_d", "A sealed hierarchy and exhaustive when checks."),
        ),
    ),
    question(
        id = "kotlin_objects_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_objects",
        text = "What is a Kotlin object declaration commonly used for?",
        correctAnswerIds = listOf("kotlin_objects_001_a"),
        explanation = "An object declaration defines a singleton instance. It is useful for stateless utilities or shared objects, but its in-memory state is still tied to the process.",
        sources = listOf(kotlinObjectSource),
        answers = listOf(
            answer("kotlin_objects_001_a", "Declaring a singleton instance."),
            answer("kotlin_objects_001_b", "Declaring a class that must be instantiated with new."),
            answer("kotlin_objects_001_c", "Creating a nullable primitive type."),
            answer("kotlin_objects_001_d", "Generating a SQL table automatically."),
        ),
    ),
    question(
        id = "kotlin_sealed_types_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_sealed_types",
        text = "Why are sealed classes or sealed interfaces useful for modeling UI states or results?",
        correctAnswerIds = listOf("kotlin_sealed_types_001_d"),
        explanation = "A sealed hierarchy restricts known direct subtypes, allowing callers to handle a closed set of cases and enabling exhaustive when expressions in many situations.",
        sources = listOf(kotlinSealedSource),
        answers = listOf(
            answer("kotlin_sealed_types_001_a", "They allow any module to add new direct subclasses at runtime."),
            answer("kotlin_sealed_types_001_b", "They make every subclass serializable without a plugin."),
            answer("kotlin_sealed_types_001_c", "They prevent all inheritance inside the same package."),
            answer("kotlin_sealed_types_001_d", "They model a restricted set of known alternatives."),
        ),
    ),
    question(
        id = "kotlin_generics_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_generics",
        text = "In Kotlin generics, what does declaration-site variance with out T indicate?",
        correctAnswerIds = listOf("kotlin_generics_001_b"),
        explanation = "An out type parameter is covariant and can be produced safely by the type. It should not be consumed in positions that would break type safety.",
        sources = listOf(kotlinGenericsSource),
        answers = listOf(
            answer("kotlin_generics_001_a", "The type parameter can only be used as a function argument."),
            answer("kotlin_generics_001_b", "The type parameter is covariant and can be safely produced."),
            answer("kotlin_generics_001_c", "The type parameter disables null-safety checks."),
            answer("kotlin_generics_001_d", "The type parameter is erased only on Android."),
        ),
    ),
    question(
        id = "kotlin_reified_types_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_reified_types",
        text = "Why can an inline function with a reified type parameter check T at runtime?",
        correctAnswerIds = listOf("kotlin_reified_types_001_c"),
        explanation = "Inlining substitutes the function body at call sites, allowing the compiler to make the actual type argument available for operations such as is checks or class references.",
        sources = listOf(kotlinInlineSource),
        answers = listOf(
            answer("kotlin_reified_types_001_a", "Because all Kotlin generic types are normally reified on the JVM."),
            answer("kotlin_reified_types_001_b", "Because reified type parameters are stored in Android resources."),
            answer("kotlin_reified_types_001_c", "Because the inline function body is expanded at call sites with the concrete type available."),
            answer("kotlin_reified_types_001_d", "Because reified works only for suspend functions."),
        ),
    ),
    question(
        id = "kotlin_equality_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_equality",
        text = "What is the difference between == and === in Kotlin?",
        correctAnswerIds = listOf("kotlin_equality_001_a"),
        explanation = "The == operator checks structural equality by calling equals with null-safety. The === operator checks referential equality, meaning whether two references point to the same object.",
        sources = listOf(kotlinEqualitySource),
        answers = listOf(
            answer("kotlin_equality_001_a", "== checks structural equality; === checks referential equality."),
            answer("kotlin_equality_001_b", "== checks referential equality; === checks structural equality."),
            answer("kotlin_equality_001_c", "Both operators always compile to the same JVM instruction."),
            answer("kotlin_equality_001_d", "=== is only available for primitive numbers."),
        ),
    ),
    question(
        id = "kotlin_scope_functions_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_scope_functions",
        text = "What is a practical risk of overusing Kotlin scope functions such as apply, also, let, run, and with?",
        correctAnswerIds = listOf("kotlin_scope_functions_001_d"),
        explanation = "Scope functions can reduce boilerplate, but excessive nesting or mixed receiver styles can make it unclear what this or it refers to and reduce readability.",
        sources = listOf(kotlinScopeFunctionsSource),
        answers = listOf(
            answer("kotlin_scope_functions_001_a", "They disable null safety inside lambdas."),
            answer("kotlin_scope_functions_001_b", "They make every lambda run on a background thread."),
            answer("kotlin_scope_functions_001_c", "They turn immutable vals into mutable vars."),
            answer("kotlin_scope_functions_001_d", "They can obscure receiver or argument meaning when nested or mixed heavily."),
        ),
    ),
    question(
        id = "kotlin_sequences_001",
        topicId = "kotlin_language",
        subtopicId = "kotlin_sequences",
        text = "When can Kotlin sequences be useful compared with eager collection operations?",
        correctAnswerIds = listOf("kotlin_sequences_001_b"),
        explanation = "Sequences evaluate operations lazily, which can avoid intermediate collections in multi-step pipelines. They are not automatically faster for every small collection.",
        sources = listOf(kotlinSequencesSource),
        answers = listOf(
            answer("kotlin_sequences_001_a", "When every element must be eagerly copied after each operation."),
            answer("kotlin_sequences_001_b", "When a multi-step pipeline can benefit from lazy evaluation and fewer intermediate collections."),
            answer("kotlin_sequences_001_c", "When code must run only on Android's main thread."),
            answer("kotlin_sequences_001_d", "When nullability checks need to be disabled."),
        ),
    ),
    question(
        id = "jvm_fundamentals_001",
        topicId = "kotlin_language",
        subtopicId = "jvm_fundamentals",
        text = "Why does JVM type erasure matter when designing generic Kotlin APIs for Android?",
        correctAnswerIds = listOf("jvm_fundamentals_001_c"),
        explanation = "Generic type arguments are generally erased at runtime on the JVM, so APIs that need runtime type information often require an explicit class/token or an inline reified function.",
        sources = listOf(kotlinGenericsSource, kotlinInlineSource),
        answers = listOf(
            answer("jvm_fundamentals_001_a", "Because erasure removes all objects from memory after compilation."),
            answer("jvm_fundamentals_001_b", "Because erasure makes nullable types impossible."),
            answer("jvm_fundamentals_001_c", "Because generic type arguments are generally not directly available at runtime."),
            answer("jvm_fundamentals_001_d", "Because erasure applies only to Compose previews."),
        ),
    ),
)
