package org.artkachenko.kmp_learning_app.curriculum.content

internal val lifecycleNavigationQuestions = listOf(
    question(
        id = "activity_lifecycle_001",
        topicId = "lifecycle_navigation",
        subtopicId = "activity_lifecycle",
        text = "Why is onPause() a poor place to perform a long database write or network request?",
        correctAnswerIds = listOf("activity_lifecycle_001_b"),
        explanation = "onPause() execution is brief and should complete quickly. Longer shutdown or persistence work should use a more appropriate lifecycle point or background/persistence mechanism.",
        sources = listOf(androidActivityLifecycleSource),
        answers = listOf(
            answer("activity_lifecycle_001_a", "Because onPause() is never called before another Activity starts."),
            answer("activity_lifecycle_001_b", "Because onPause() should be brief and long work may not complete before the transition continues."),
            answer("activity_lifecycle_001_c", "Because onPause() always runs on a background thread."),
            answer("activity_lifecycle_001_d", "Because onPause() is called only after process death."),
        ),
    ),
    question(
        id = "fragment_lifecycle_001",
        topicId = "lifecycle_navigation",
        subtopicId = "fragment_lifecycle",
        text = "In a Fragment that uses Views, why should view references normally be cleared in onDestroyView() rather than onDestroy()?",
        correctAnswerIds = listOf("fragment_lifecycle_001_a"),
        explanation = "A Fragment instance can outlive its View hierarchy. Clearing View references when the view is destroyed prevents retaining obsolete Views and their Activity context.",
        sources = listOf(androidFragmentLifecycleSource),
        answers = listOf(
            answer("fragment_lifecycle_001_a", "Because the Fragment's View lifecycle can end before the Fragment instance is destroyed."),
            answer("fragment_lifecycle_001_b", "Because onDestroy() is never called for Fragments."),
            answer("fragment_lifecycle_001_c", "Because View references are valid until the process dies."),
            answer("fragment_lifecycle_001_d", "Because onDestroyView() runs only during configuration changes."),
        ),
    ),
    question(
        id = "configuration_changes_001",
        topicId = "lifecycle_navigation",
        subtopicId = "configuration_changes",
        text = "What usually happens to an Activity during an unhandled configuration change such as rotation?",
        correctAnswerIds = listOf("configuration_changes_001_c"),
        explanation = "By default, Android destroys and recreates the Activity for configuration changes. UI should be rebuilt from appropriate state rather than relying on old Activity fields.",
        sources = listOf(androidStateChangesSource),
        answers = listOf(
            answer("configuration_changes_001_a", "The same Activity instance continues without lifecycle callbacks."),
            answer("configuration_changes_001_b", "Only onResume() is called again."),
            answer("configuration_changes_001_c", "The Activity is destroyed and a new instance is created."),
            answer("configuration_changes_001_d", "The process is always killed before the Activity is recreated."),
        ),
    ),
    question(
        id = "process_death_001",
        topicId = "lifecycle_navigation",
        subtopicId = "process_death",
        text = "Why can a ViewModel preserve UI state across rotation but not by itself guarantee recovery after system-initiated process death?",
        correctAnswerIds = listOf("process_death_001_d"),
        explanation = "ViewModels are retained in memory across configuration changes, but memory is lost when the process is killed. State that must recover after process death needs saved state or persistent storage.",
        sources = listOf(androidSaveUiStateSource),
        answers = listOf(
            answer("process_death_001_a", "Because ViewModels are serialized into the manifest only during rotation."),
            answer("process_death_001_b", "Because ViewModels are scoped to a View and Views are never recreated."),
            answer("process_death_001_c", "Because process death preserves Activity fields but not ViewModels."),
            answer("process_death_001_d", "Because ViewModels are in-memory objects and process death clears that memory."),
        ),
    ),
    question(
        id = "saved_state_001",
        topicId = "lifecycle_navigation",
        subtopicId = "saved_state",
        text = "Which kind of state is a good candidate for saved-state APIs such as rememberSaveable or SavedStateHandle?",
        correctAnswerIds = listOf("saved_state_001_a"),
        explanation = "Saved-state APIs are intended for small pieces of transient UI state needed to recreate the user's place. Large datasets or durable app data should use persistence.",
        sources = listOf(androidSaveUiStateSource),
        answers = listOf(
            answer("saved_state_001_a", "Small transient UI state needed to restore the screen after recreation."),
            answer("saved_state_001_b", "Large cached API responses that must be queried offline."),
            answer("saved_state_001_c", "Open socket connections that should survive process death."),
            answer("saved_state_001_d", "All repository data because saved state replaces local storage."),
        ),
    ),
    question(
        id = "navigation_fundamentals_001",
        topicId = "lifecycle_navigation",
        subtopicId = "navigation_fundamentals",
        text = "What does a navigation back stack primarily represent?",
        correctAnswerIds = listOf("navigation_fundamentals_001_b"),
        explanation = "A back stack records destinations or entries in navigation order. Pushing a destination moves forward, and popping the top entry returns to the previous destination.",
        sources = listOf(androidNavigationSource),
        answers = listOf(
            answer("navigation_fundamentals_001_a", "A cache of every ViewModel created by the app."),
            answer("navigation_fundamentals_001_b", "An ordered history of navigation entries used to determine the current and previous destinations."),
            answer("navigation_fundamentals_001_c", "A list of all installed apps that can handle an Intent."),
            answer("navigation_fundamentals_001_d", "A set of resources selected for the current configuration."),
        ),
    ),
    question(
        id = "back_handling_001",
        topicId = "lifecycle_navigation",
        subtopicId = "back_handling",
        text = "In a typical single-stack navigation flow, what should happen when the user presses Back from a detail destination that was pushed from a list destination?",
        correctAnswerIds = listOf("back_handling_001_c"),
        explanation = "Back should remove the current top entry and reveal the previous entry. It should not create a second copy of the list destination or clear unrelated application state.",
        sources = listOf(androidNavigationSource),
        answers = listOf(
            answer("back_handling_001_a", "Push a new copy of the list destination."),
            answer("back_handling_001_b", "Restart the application process."),
            answer("back_handling_001_c", "Pop the detail entry so the previous list entry becomes current again."),
            answer("back_handling_001_d", "Clear every ViewModel in the application."),
        ),
    ),
)
