package org.artkachenko.kmp_learning_app.curriculum.content

internal val networkingQuestions = listOf(
    question(
        id = "http_idempotency_001",
        topicId = "networking",
        subtopicId = "http_idempotency",
        text = "Why does HTTP idempotency matter when designing retry behavior?",
        correctAnswerIds = listOf("http_idempotency_001_c"),
        explanation = "Idempotent operations can be repeated with the same intended effect, making retries safer. Retrying non-idempotent operations such as many POST requests can duplicate side effects unless designed carefully.",
        sources = listOf(httpSemanticsSource),
        answers = listOf(
            answer("http_idempotency_001_a", "It means the request never reaches the server."),
            answer("http_idempotency_001_b", "It means every method is safe to retry forever."),
            answer("http_idempotency_001_c", "It helps determine whether retrying a request may repeat unintended side effects."),
            answer("http_idempotency_001_d", "It applies only to WebSocket messages."),
        ),
    ),
    question(
        id = "network_timeouts_001",
        topicId = "networking",
        subtopicId = "network_timeouts",
        text = "Why should Android network clients configure timeouts?",
        correctAnswerIds = listOf("network_timeouts_001_b"),
        explanation = "Timeouts bound how long the app waits for connection, reading, or writing. Without them, calls can hang too long and degrade user experience or resource usage.",
        sources = listOf(okhttpSource),
        answers = listOf(
            answer("network_timeouts_001_a", "To make TLS optional."),
            answer("network_timeouts_001_b", "To bound waiting time for network operations that may stall."),
            answer("network_timeouts_001_c", "To force every response into the disk cache."),
            answer("network_timeouts_001_d", "To make all HTTP methods idempotent."),
        ),
    ),
    question(
        id = "okhttp_interceptors_001",
        topicId = "networking",
        subtopicId = "okhttp_interceptors",
        text = "What is a common use of an OkHttp interceptor?",
        correctAnswerIds = listOf("okhttp_interceptors_001_a"),
        explanation = "Interceptors can observe, modify, and retry requests/responses. Common uses include adding headers, logging, and handling authentication concerns.",
        sources = listOf(okhttpSource),
        answers = listOf(
            answer("okhttp_interceptors_001_a", "Adding headers or observing/modifying requests and responses."),
            answer("okhttp_interceptors_001_b", "Declaring Room entities."),
            answer("okhttp_interceptors_001_c", "Rendering Compose layouts."),
            answer("okhttp_interceptors_001_d", "Replacing Gradle dependency resolution."),
        ),
    ),
    question(
        id = "retrofit_coroutines_001",
        topicId = "networking",
        subtopicId = "retrofit_coroutines",
        text = "What is the benefit of declaring Retrofit service functions as suspend functions?",
        correctAnswerIds = listOf("retrofit_coroutines_001_d"),
        explanation = "Suspend service functions integrate network calls into coroutine code without blocking the calling thread, letting callers use structured coroutine handling.",
        sources = listOf(retrofitSource, coroutinesBasicsSource),
        answers = listOf(
            answer("retrofit_coroutines_001_a", "They make HTTP responses impossible to fail."),
            answer("retrofit_coroutines_001_b", "They force the call to run on the main thread."),
            answer("retrofit_coroutines_001_c", "They remove the need to parse response bodies."),
            answer("retrofit_coroutines_001_d", "They integrate asynchronous calls with coroutine suspension."),
        ),
    ),
    question(
        id = "kotlinx_serialization_001",
        topicId = "networking",
        subtopicId = "kotlinx_serialization",
        text = "What is a key difference between kotlinx.serialization and reflection-heavy JSON libraries?",
        correctAnswerIds = listOf("kotlinx_serialization_001_b"),
        explanation = "kotlinx.serialization uses compiler-generated serializers for annotated models and is designed for Kotlin multiplatform use, rather than depending primarily on runtime reflection.",
        sources = listOf(kotlinxSerializationSource),
        answers = listOf(
            answer("kotlinx_serialization_001_a", "It works only on Android and cannot be used in common code."),
            answer("kotlinx_serialization_001_b", "It uses compiler-assisted serializers and supports Kotlin Multiplatform."),
            answer("kotlinx_serialization_001_c", "It requires every model to be a Room entity."),
            answer("kotlinx_serialization_001_d", "It serializes only XML resources."),
        ),
    ),
)

