package org.artkachenko.kmp_learning_app.curriculum.content

internal val testingQuestions = listOf(
    question(
        id = "testing_strategy_001",
        topicId = "testing",
        subtopicId = "testing_strategy",
        text = "Why should Android test strategy include more than only end-to-end UI tests?",
        correctAnswerIds = listOf("testing_strategy_001_b"),
        explanation = "Lower-level tests are usually faster, more focused, and better at isolating failures. UI tests are valuable but slower and more brittle when used as the only safety net.",
        sources = listOf(androidTestingSource),
        answers = listOf(
            answer("testing_strategy_001_a", "Because UI tests cannot interact with Android views."),
            answer("testing_strategy_001_b", "Because focused lower-level tests are faster and isolate failures more precisely."),
            answer("testing_strategy_001_c", "Because unit tests replace all integration tests."),
            answer("testing_strategy_001_d", "Because Compose code cannot be tested."),
        ),
    ),
    question(
        id = "test_doubles_001",
        topicId = "testing",
        subtopicId = "test_doubles",
        text = "What is a common reason to use a fake implementation in a unit test?",
        correctAnswerIds = listOf("test_doubles_001_c"),
        explanation = "A fake can provide deterministic behavior for a dependency while preserving a realistic contract, making the class under test easier to exercise.",
        sources = listOf(androidTestingSource),
        answers = listOf(
            answer("test_doubles_001_a", "To make the test depend on the production server."),
            answer("test_doubles_001_b", "To hide all assertions."),
            answer("test_doubles_001_c", "To replace a dependency with deterministic behavior under test."),
            answer("test_doubles_001_d", "To force every test to be instrumented."),
        ),
    ),
    question(
        id = "viewmodel_testing_001",
        topicId = "testing",
        subtopicId = "viewmodel_testing",
        text = "Why are ViewModels often good candidates for local unit tests?",
        correctAnswerIds = listOf("viewmodel_testing_001_a"),
        explanation = "ViewModels can expose state and handle events without depending directly on rendering. With dependencies injected, their state transitions can be tested locally.",
        sources = listOf(androidTestingSource, composeStateHoistingSource),
        answers = listOf(
            answer("viewmodel_testing_001_a", "Their state transitions can often be tested without rendering UI."),
            answer("viewmodel_testing_001_b", "They require a physical device for every assertion."),
            answer("viewmodel_testing_001_c", "They cannot accept fake dependencies."),
            answer("viewmodel_testing_001_d", "They are recreated after every function call."),
        ),
    ),
    question(
        id = "coroutine_testing_001",
        topicId = "testing",
        subtopicId = "coroutine_testing",
        text = "What is the purpose of runTest in coroutine tests?",
        correctAnswerIds = listOf("coroutine_testing_001_d"),
        explanation = "runTest provides a coroutine test scope and scheduler support so suspending code can be tested deterministically, including virtual-time behavior.",
        sources = listOf(coroutineTestingSource),
        answers = listOf(
            answer("coroutine_testing_001_a", "To run tests only on Android devices."),
            answer("coroutine_testing_001_b", "To disable coroutine cancellation."),
            answer("coroutine_testing_001_c", "To make all delays sleep the real thread."),
            answer("coroutine_testing_001_d", "To test suspending code with a controlled coroutine test environment."),
        ),
    ),
    question(
        id = "compose_ui_testing_001",
        topicId = "testing",
        subtopicId = "compose_ui_testing",
        text = "Why do Compose UI tests often query by semantics rather than implementation details?",
        correctAnswerIds = listOf("compose_ui_testing_001_b"),
        explanation = "Semantics represent user-visible meaning and actions. Querying semantics makes tests align better with accessibility and behavior than with internal layout structure.",
        sources = listOf(composeTestingSource, composeAccessibilitySource),
        answers = listOf(
            answer("compose_ui_testing_001_a", "Because semantics are private compiler metadata."),
            answer("compose_ui_testing_001_b", "Because semantics expose meaningful UI information for testing and accessibility."),
            answer("compose_ui_testing_001_c", "Because semantics replace all assertions."),
            answer("compose_ui_testing_001_d", "Because Compose tests cannot click buttons."),
        ),
    ),
)

